function requireAll()
    require("utils")
    require("background")
    require("obstacles")
    require("obstacle")
    require("pipe")
    require("player")
    require("score")
    require("save")
    require("gameover")
    require("menu")
    require("ai")
    require("pause")
    require("credits")
end

requireAll()