require('src/game-states/GameState')
require('src/game-states/ClassicState')
require('src/game-states/ColorsState')
require('src/game-states/CreditsState')
require('src/game-states/GameOverState')
require('src/game-states/MenuState')
require('src/game-states/PausedState')
require('src/game-states/StoreState')