require('src/BattleStick/battlestickplayer')
require('src/BattleStick/enemy')
require('src/BattleStick/shot')
require('src/BattleStick/battlecoins')
require('src/BattleStick/battleobstacles')
require('src/BattleStick/battlestickgameover')
require('src/BattleStick/battlescore')